base_url = "http://localhost"

title = "Fauzy's Blog"
description = "FOSS • Linux • Programming"

default_language = "en"
theme = "after-dark"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [{ name = "categories", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "axar"

[extra]
author = "Fauzy Madani"
after_dark_menu = [
  { name = "Home", url = "$BASE_URL" },
  { name = "Categories", url = "$BASE_URL/categories" },
  { name = "Source", url = "https://github.com/fauzymadani/personalBlog" },
  { name = "GitHub", url = "https://github.com/fauzymadani" },
]
after_dark_title = "Fauzy's Blog | FOSS • Linux • Programming"

